# Generated by Django 4.1a1 on 2022-12-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="qty",
            field=models.IntegerField(null=True),
        ),
    ]
