# Generated by Django 4.0 on 2022-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
