# Generated by Django 4.1a1 on 2022-12-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("alamat", models.CharField(max_length=35)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telepon", models.CharField(max_length=10)),
                (
                    "image",
                    models.ImageField(
                        default="image/default.png", upload_to="supplier/image"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
